#ifndef BUILDALLBUTTON_GLOBAL_H
#define BUILDALLBUTTON_GLOBAL_H

#include <QtGlobal>

#if defined(BUILDALLBUTTON_LIBRARY)
#  define BUILDALLBUTTONSHARED_EXPORT Q_DECL_EXPORT
#else
#  define BUILDALLBUTTONSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // BUILDALLBUTTON_GLOBAL_H

